api = "https://deepl.deno.dev/translate"

[window]
# 字体放大，设置为负数就缩小
font_size_plus = 3
theme = "dark" # light or dark

# 窗口大小，可以设置成适合自己屏幕的大小
[window.size]
width = 700
height = 300

[hotkey]
launch = "CTRL+Q"
quit = "CTRL+SHIFT+D"
